kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: ingress
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
        - image: {{ traefik }}
          name: traefik-ingress-lb
          ports:
          - name: http
            containerPort: 80
            hostPort: 80
          - name: admin
            containerPort: 8080
            hostPort: 8080
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          args:
            - --web
            - --kubernetes
            - --web.metrics
            - --web.metrics.prometheus
            - --defaultentrypoints=http,https
            - --entrypoints=Name:https Address::443 TLS
            - --entrypoints=Name:http Address::80
            - --accesslog
            - --accessLog.format="json"
            - --accesslog.filepath=/var/log/traefik/access.log
            - --traefiklog
            - --traefikLog.format="json"
            - --traefiklog.filepath=/var/log/traefik/traefik.log
            - --traefiklogsfile=traefik.log
            - --api
            - --loglevel=INFO
            - --metrics.prometheus
          volumeMounts:
            - name: log
              mountPath: /var/log/traefik
      volumes:
        - name: log
          hostPath:
            path: /var/log/traefik