apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
  namespace: registry
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi