
# Ingress Nginx
- name: Ingress Controller Nginx step 1/2
  template:
    src: '{{ item }}'
    dest: /usr/local/src/kubernetes/ingressnginx/
  with_items:
    - ingressnginx/1.Namespace.yaml
    - ingressnginx/2.RBAC.yaml
    - ingressnginx/3.ServiceAccount.yaml
    - ingressnginx/4.ConfigMap.yaml
    - ingressnginx/5.Service.yaml
    - ingressnginx/6.Deployment.yaml

- name: Ingress Controller Nginx step 2/2
  command: kubectl apply -f /usr/local/src/kubernetes/ingressnginx
  run_once: true
  when: IngressController == "nginx"

- name: Ingress Controller Traefik step 1/2
  template:
    src: '{{ item }}'
    dest: /usr/local/src/kubernetes/Traefik/
  with_items:
    - Traefik/1.Namespace.yaml
    - Traefik/2.ClusterRole.yaml
    - Traefik/3.ServiceAccount.yaml
    - Traefik/4.DaemonSet.yaml
    - Traefik/5.Service.yaml
    - Traefik/6.Ingress.yaml

- name: Ingress Controller Traefik step 2/2
  command: kubectl apply -f /usr/local/src/kubernetes/Traefik/
  run_once: true
  when: IngressController == "traefik"