---
# This Playbook Install Kubernetes Addon

# flannel
- name: Kubernetes Addon Flannel
  include_tasks: Flannel.yaml

# calico
- name: Kubernetes Addon Calico
  include_tasks: Calico.yaml

# coredns
- name: Kubernetes Addon CoreDNS
  include_tasks: CoreDNS.yaml

# kubedns
- name: Kubernetes Addon KubeDNS
  include_tasks: KubeDNS.yaml

# metrics-server
- name: Kubernetes Addon Metrics Server
  include_tasks: MetricsServer.yaml

# Dashboard
- name: Kubernetes Addon Dashboard
  include_tasks: Dashboard.yaml

# IngressNginx
- name: Kubernetes Addon Ingress Controller
  include_tasks: IngressController.yaml

# WeaveScope
- name: Kubernetes Addon WeaveScope
  include_tasks: WeaveScope.yaml

# NFS
- name: Kubernetes Addon NFS
  include_tasks: NFS.yaml

# HelmTiller
- name: Kubernetes Addon HelmTiller
  include_tasks: HelmTiller.yaml

# EFK
- name: Kubernetes Addon EFK
  include_tasks: EFK.yaml

# Example
- name: Kubernetes Example
  include_tasks: example.yaml

# Done
- name: Kubernetes Cluster Information
  include_tasks: Done.yaml