---
# This Playbook Install and Config Etcd Server
# 安装haproxy
- include_tasks: haproxy.yaml
  when: slb == "haproxy"


- include_tasks: nginx.yaml
  when: slb == "nginx"

# 安装keepalived
- include_tasks: keepalived.yaml